apiVersion: apps/v1
kind: Deployment
metadata:
  name: flown
  labels:
    app: flown
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flown
  template:
    metadata:
      labels:
        app: flown
        tier: flown
    spec:
      containers:
      - name: flown-test
        image: sdvr/flown-cicd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: flown
---
apiVersion: v1
kind: Service
metadata:
  name: flown
  labels:
    app: flown
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: flown
    tier: flown
  type: LoadBalancer
